config/routes.rb
Rails.application.routes.draw do
  resources :shorteners, except: [:edit, :update]
  
  root "shorteners#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortener.rb
class Shortener < ApplicationRecord
  serialize :alt_domain, Array

  validates :main_domain, :abbrev, presence: true
  validates_uniqueness_of :main_domain, :abbrev

  def self.abbreviate_url(main_domain)
    domain = get_host_without_www(main_domain)
    shortener = Shortener.where(main_domain: domain).first
    if shortener.blank?
      shortener = Shortener.new(main_domain: domain, abbrev: get_available_abbr(domain))
    end
    shortener.alt_domain = (shortener.alt_domain + [main_domain]).uniq
    return shortener
  end

  private

    # Only parses twice if url doesn't start with a scheme
    def self.get_host_without_www(url)
      uri = URI.parse(url)
      uri = URI.parse("http://#{url}") if uri.scheme.nil?
      host = uri.host.downcase
      host.start_with?('www.') ? host[4..-1] : host
    end

    def self.get_available_abbr(domain)
      abbr = domain.gsub(/[[:alpha:]]{4,}/) { |s| "%s%d%s" % [s[0], s.size-2, s[-1]] }
      while Shortener.where(abbrev: abbr).where.not(main_domain: domain).present?
        abbr += rand(10).to_s
      end
      return abbr
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  before_action :set_shortener, only: [:show, :destroy]

  # GET /shorteners
  # GET /shorteners.json
  def index
    @shorteners = Shortener.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  # GET /shorteners/new
  def new
    @shortener = Shortener.new
  end

  # POST /shorteners
  # POST /shorteners.json
  def create
    unless params[:shortener][:main_domain].blank?
      @shortener = Shortener.abbreviate_url(params[:shortener][:main_domain])

      if @shortener.save
        redirect_to root_path, notice: 'Shortener was successfully created.'
      else
        redirect_to root_path, alert: "#{@shortener.errors.full_messages.join(', ')}"
      end
    else
      redirect_to root_path, alert: "URL can't be blank."
    end
  end

  # DELETE /shorteners/1
  # DELETE /shorteners/1.json
  def destroy
    @shortener.destroy
    redirect_to shorteners_url, notice: 'Shortener was successfully removed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortener
      @shortener = Shortener.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alert_notification.html.erb
<div class='container-fluid'>
  <% if notice %>
    <div id="success" class="row alert alert-success rounded alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <center><%= notice %></center>
    </div>
  <% end %>
  <% if alert %>
    <div id="error" class="row alert alert-danger rounded alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <center><%= alert %></center>
    </div>
  <% end %>
</div>

app/views/layouts/_footer_navbar.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link">All Rights Reserved &copy; <%= Date.today.year %> & Powered by</a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to '<i class="fa fa fa-github"></i> Manjunath P'.html_safe, "https://github.com/manjunath724", target: :_blank, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_header_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand">
    <i class="fa fa fa-flash"></i>
    URL Shortener
  </a>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to '<i class="fa fa fa-home"></i> Home'.html_safe, root_path, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>| URL Shortener |</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header_navbar' %>

    <div class="container container-main">
      <%= render 'layouts/alert_notification' %>

      <%= yield %>

      <br><br>
    </div>

    <%= render 'layouts/footer_navbar' %>
  </body>
</html>

app/views/shorteners/_form.html.erb
<%= form_with(model: shortener, local: true, html: { class: 'form-horizontal' }) do |form| %>
  <% if shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% shortener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :main_domain, "URL" %><br>
    <%= form.text_field :main_domain, class: 'form-control' %>
  </div>

  <div class="actions"><br>
    <%= form.submit class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/shorteners/index.html.erb
<div id="header-section">
  <h1>Shorteners (<%= @shorteners.total_count %>)</h1>

  <p class="pull-right">
    <%= link_to 'Add New', new_shortener_path, class: 'btn btn-sm btn-success' %>
  </p>
</div>
<br>

<div class="table-responsive-sm">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Main Domain</th>
        <th>Abbreviation</th>
        <th>Alternate Domain</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @shorteners.each do |shortener| %>
        <tr>
          <td><%= shortener.main_domain %></td>
          <td><%= link_to shortener.abbrev, "//#{shortener.main_domain}", target: :_blank %></td>
          <td><li><%= shortener.alt_domain.join('<li>').html_safe %></td>
          <td>
            <%= link_to 'Remove', shortener, id: "remove-#{shortener.id}", method: :delete, 
                data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @shorteners, class: 'pagination', theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>

<br><br>

app/views/shorteners/new.html.erb
<div class="col-md-8 col-4 mx-auto">
  <h1>New Shortener</h1>

  <%= render 'form', shortener: @shortener %>
</div>

app/views/shorteners/show.html.erb
<p>
  <strong>Main Domain:</strong>
  <%= @shortener.main_domain %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= link_to @shortener.abbrev, "//#{@shortener.main_domain}", target: :_blank %>
</p>

<p>
  <strong>Alternate Domain:</strong>
  <ul>
    <% @shortener.alt_domain.each do |d| %>
      <li><%= d %></li>
    <% end %>
  </ul>
</p>